### ISSUE TITLE
Getting "ghc: missing -B<dir> option"

### ISSUE THREAD

**Issue by Tehnix** [mobilehaskell/hackage-overlay#1]
Toying with the compiler after having read https://medium.com/@zw3rk/ghc-cross-compiler-binary-distributions-490bb2c0c411. 

Host: macOS High Sierra
Target: iOS Simulator (x86_64-apple-ios)

I did the following:

1. Installed LLVM5 via `brew install llvm`
2. git cloned down https://github.com/zw3rk/toolchain-wrapper.git and did `./bootstrap`
3. Exported paths `export PATH="$(PWD)/toolchain-wrapper:/usr/local/opt/llvm/bin:$PATH"` inside the toolchain dir
4. Fetched ghc-8.3.20171020-x86_64-apple-ios.tar.xz from http://hackage.mobilehaskell.org
5. Did `./configure` with no options in the unpacked ghc-8.3.20171020
6. `ghc LengthTest.hs` on a Haskell file and got `ghc: missing -B<dir> option`

In step 5, when I supplied configure options via `./configure --prefix=/Users/tehnix/GitHub/Clones/toolchain-wrapper/ghc-8.3.20171020/ios-ghc --target=x86_64-apple-ios --host=x86_64-apple-darwin --build=x86_64-apple-darwin` it would oddly complain  with`configure: error: cannot find ar in your PATH, no idea how to make a library`.

Can it be that the GHC error is because something went wrong earlier in the configure since I only got it working without the parameters?

**Comment by angerman** [comment]
Hmm... there should be `x86_64-apple-ios-ar` and others in your `$PATH` after running `./bootstrap`. Could you verify that those are generated by the `bootstrap` script?

`./configure` should then pick them up properly.

**Comment by angerman** [comment]
Step 5 would also require `make install` (which should put tine binaries into `/Users/tehnix/GitHub/Clones/toolchain-wrapper/ghc-8.3.20171020/ios-ghc`)

As such you should then run
```
$ /Users/tehnix/GitHub/Clones/toolchain-wrapper/ghc-8.3.20171020/ios-ghc/bin/x86_64-apple-ios-ghc LengthTest.hs
```

**Comment by Tehnix** [comment]
Yeah, they are getting built, but not picked up. Notably there isn't any ios configs generated, could that perhaps be it?

```
λ Clones/toolchain-wrapper ‹master!› ls
README.md                               arm-linux-gnueabihf-ranlib
aarch64-apple-ios-ar                    armv7-linux-androideabi-ar
aarch64-apple-ios-cabal                 armv7-linux-androideabi-cabal
aarch64-apple-ios-clang                 armv7-linux-androideabi-clang
aarch64-apple-ios-ld                    armv7-linux-androideabi-ld
aarch64-apple-ios-ld.gold               armv7-linux-androideabi-ld.gold
aarch64-apple-ios-nm                    armv7-linux-androideabi-libtool
aarch64-apple-ios-ranlib                armv7-linux-androideabi-nm
aarch64-linux-android-ar                armv7-linux-androideabi-ranlib
aarch64-linux-android-cabal             bootstrap
aarch64-linux-android-clang             ghc-8.3.20171020
aarch64-linux-android-ld                ghc-8.3.20171020 (iOS Device aka aarch)
aarch64-linux-android-ld.gold           libtool-lite
aarch64-linux-android-libtool           linux-android-toolchain.config
aarch64-linux-android-nm                raspberrypi-toolchain.config
aarch64-linux-android-ranlib            setup.sh
android-toolchain.config                wrapper
arm-linux-gnueabihf-ar                  x86_64-apple-ios-ar
arm-linux-gnueabihf-cabal               x86_64-apple-ios-cabal
arm-linux-gnueabihf-clang               x86_64-apple-ios-clang
arm-linux-gnueabihf-ld                  x86_64-apple-ios-ld
arm-linux-gnueabihf-ld.gold             x86_64-apple-ios-ld.gold
arm-linux-gnueabihf-libtool             x86_64-apple-ios-nm
arm-linux-gnueabihf-nm                  x86_64-apple-ios-ranlib
```

**Comment by Tehnix** [comment]
Ah, never mind, stupid me. I had been exporting path as `export PATH="$(PWD)/toolchain-wrapper", but `$(PWD)` already contains the toolchain-wrapper because I was running it inside the directory. It is linking correctly now, which makes the build work with the original configure parameters.

~Next problem is now `x86_64-apple-ios-ghc LengthTest.hs` results in ...~

Got it working! Just needed to remember having the LLVM, the ios-ghc/bin dir and the toolchain-wrapper in PATH :)

**Comment by angerman** [comment]
You are missing the llvm binaries in path. `opt` and `llc` are part of llvm. Homebrew doesn’t put them in PATH by default, I assume.

**Comment by Tehnix** [comment]
@angerman yeah, exactly what happened (was rushing a bit in my excitement). Do you have any posts on what the next steps are to get the program over in the iOS Simulator for example? Currently I just have the `.o`/`.hi` files.

**Comment by angerman** [comment]
You can use the `-staticlib` flag to ghc to produce a static archive (`.a`) and link that with you iOS app.

I plan to write up more over the next few weeks. You might find some slightly older articles on medium.com/@zw3rk that should give you a jump start with the `hs_init` and foreign export needs.

**Comment by angerman** [comment]
Specifically see https://medium.com/@zw3rk/a-haskell-cross-compiler-for-ios-7cc009abe208

**Comment by Tehnix** [comment]
Thanks! 

Btw, I made https://gist.github.com/Tehnix/dd8a71322744bb92ef3176ebc6f0b7f9 to make it a bit easier to set everything up, and take care of getting the right paths in when building for whatever architecture.

**Comment by angerman** [comment]
That is pretty cool. I think two of the targets are still slightly wrong.
The 32bit android should be `armv7-linux-androideabi`, and the raspberry pi one should be `arm-linux-gnueabihf`.

Would you mind, if I include that script into the repository? Would you mind opening a PR with the script in `./scripts`?

**Comment by Tehnix** [comment]
@angerman ah, I'll update it

Yeah sure! I'll make a PR in a moment :)

**Comment by Tehnix** [comment]
@angerman did you mean a PR to this repository or the toolchain-wrapper?

**Comment by angerman** [comment]
This one

**Comment by Tehnix** [comment]
I'll close this one since we've moved the discussion to #4 .
